key:
  postImgUrl: https://ggongpang.com/postImg/
  postImgPath: /var/www/ggongpang.com/postImg/
  bannerImgUrl: https://ggongpang.com/bannerImg/
  bannerImgPath: /var/www/ggongpang.com/bannerImg/
  signupPoint: 20
  loginPoint: 10
  savePostPoint: 50
  saveCommentPoint: 20
  savePromotionPoint: -50


spring:
  config:
    import:
      - classpath:/app/security/security.yml

  profiles:
    active: prod

  mvc:
    converters:
      preferred-jason-mapper: gson

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    hikari:
      connectionTimeout: 10000
      idleTimeout: 600000
      maximum-pool-size: 300
      minimum-idle: 5
      maxLifetime: 10000
      leak-detection-threshold: 2000

  jpa:
    generate-ddl: true
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: Asia/Seoul

  servlet:
    multipart:
      max-file-size: 20MB
      enabled: true
      max-request-size: 20MB

  web:
    resources:
      static-locations: file:///var/www/ggongpang.com/postImg/, file:///var/www/ggongpang.com/bannerImg/




server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true



